name: Schedule Workflow by Ali

on:
  schedule: 
    - cron: "15 7 11 1 *"
jobs:
  Print_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Step
        run: echo 'First Schedule workflow'
      
